import React from "react";
import "./style.css";
import { Helmet, HelmetProvider } from "react-helmet-async";
import { Container, Row, Col } from "react-bootstrap";
import { dataportfolio, meta } from "../../content_option";

const project2photos = [
{
  img: "https://picsum.photos/400/800/?grayscale",
  description: "Execution and Analysis of WannaCry Ransomware",
  link: "https://youtu.be/MQgmoUdVD4A",
},
];


export const Project2 = () => {
  return (
    <HelmetProvider>
      <Container className="About-header">
        <Helmet>
          <meta charSet="utf-8" />
          <title> Execution and Analysis of WannaCry Ransomware | {meta.title} </title>{" "}
          <meta name="description" content={meta.description} />
        </Helmet>
        <Row className="mb-5 mt-3 pt-md-3">
          <Col lg="8">
            <h1 className="display-4 mb-4">  </h1>{" "}
            <hr className="t_border my-4 ml-0 text-left" />
          </Col>
        </Row>
        <div className="mb-5 po_items_hoPROJECT1">
          {project2photos.map((data, i) => {
            return (
              <div key={i} className="po_itemPROJECT1">
                  <div className="display-6 mb-3">Execution and Analysis of WannaCry Ransomware Sample from Zoo in Air-Gapped Environment</div>
                  
                  <iframe
                    width="100%"
                    height="315"
                    src="https://www.youtube.com/embed/MQgmoUdVD4A?autoplay=1&mute=1"
                    title="YouTube video"
                    frameBorder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                    allowFullScreen
                    style={{ maxWidth: "600px" }}
                  ></iframe>

                  <div className="po_itemPROJECT2">This is the presentation conducted with fellow Cybersecurity students Johanna Needham and  Christopher Silva. The above video shows my portion where I set up a secure, air-gapped virtual environment using VMware to safely execute and analyze WannaCry ransomware. Using REMnux and INetSim, I monitored the malware’s behavior, network activity, and encryption process, all while preserving isolation and reverting to clean VM snapshots for safe reanalysis.</div>
                  <div className="display-6 mb-3">INetSim Running in REMnux Terminal</div>
                  <img  className="po_itemPROJECT2" src="https://res.cloudinary.com/drewskljl/image/upload/v1745105193/Screenshot_2025-04-19_192535_fm2t23.png" />
                  <div className="po_itemPROJECT2">
                  INetSim was launched on the REMnux VM to act as a fake internet environment. It handled DNS queries, HTTP requests, and other protocol responses generated by the malware. This allowed WannaCry to behave as if it had a real internet connection—without any external risk.</div>
                  <div className="display-6 mb-3">INetSim Running in REMnux Terminal</div>
                  <img  className="po_itemPROJECT2" src="https://res.cloudinary.com/drewskljl/image/upload/v1745105547/Screenshot_2024-11-30_131149_r3szex.png" />
                  <div className="po_itemPROJECT2">INetSim was used to simulate internet services locally, allowing the malware to resolve DNS and attempt connections in a safe, controlled lab environment.</div>
                  <div className="display-6 mb-3">Wireshark Capture of WannaCry Network Activity</div>
                  <img  className="po_itemPROJECT2" src="https://res.cloudinary.com/drewskljl/image/upload/v1745105835/Screenshot_2024-12-07_004138highlight_zbsvkb.png" />
                  <div className="po_itemPROJECT2">Wireshark, running on REMnux, captured real-time traffic from the infected Windows VM. Notable patterns included DNS queries and SMBv1 exploit attempts — key indicators of WannaCry’s worm-like spread and ransomware behavior.</div>
                  <div className="display-6 mb-3">WannaCry Execution on Flare VM (Windows 10)</div>
                  <img  className="po_itemPROJECT2" src="https://res.cloudinary.com/drewskljl/image/upload/v1745105980/Screenshot_2024-12-07_011010_ukomp9.png" />
                  <div className="po_itemPROJECT2">WannaCry was executed inside a Flare VM instance running on Windows 10. The system was made non-persistent and fully isolated. Flare VM's built-in tools allowed for safe inspection, system monitoring, and preparation for deeper analysis.</div>
                  <div className="display-6 mb-3">Static Malware Analysis with Ghidra</div>
                  <img  className="po_itemPROJECT2" src="https://res.cloudinary.com/drewskljl/image/upload/v1745106361/Screenshot_2025-04-19_194535_t903nh.png" />
                  <div className="po_itemPROJECT2">After capturing behavior and IOCs, I loaded the WannaCry binary into Ghidra for static analysis. This provided deeper insight into the ransomware’s encryption routines, obfuscated code structures, and hardcoded network behavior.</div>
                  <div className="display-6 mb-3">Directory View of theZoo Malware Sample</div>
                  <img  className="po_itemPROJECT2" src="https://res.cloudinary.com/drewskljl/image/upload/v1745106610/Screenshot_2024-12-05_190405highlight_ka9xui.png" />
                  <div className="po_itemPROJECT2">The WannaCry sample was securely downloaded from the open-source malware archive theZoo. The extracted binary was verified, hashed, and stored in a secure offline directory prior to execution.</div>
              </div>
              
            );
          })}
        </div>
      </Container>
    </HelmetProvider>
  );
};
